version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: scada_repo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: scada_repo
      DATABASE_URL: "postgres://postgres:pass@db:5432/scada_repo"
    ports:
      - "4020:4020"
      - "853:853"
    entrypoint: ["/app/entrypoint.sh"]

volumes:
  db_data: