version: '3.8'
networks:
  global:

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: scada_repo
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - global
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"]

  app:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: scada_repo
      DATABASE_URL: "postgres://postgres:pass@db:5432/scada_repo"
    networks:
      - global
    ports:
      - "4020:4020"
    entrypoint: ["/app/entrypoint.sh"]

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    networks:
      - global
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true

volumes:
  db_data:
  grafana_data:

cadvisor:
  image: gcr.io/cadvisor/cadvisor:latest
  ports:
    - "8080:8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  networks:
    - global
