version: '3.8'
networks:
  global:

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: scada_repo
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - global
    ports:
      - "127.0.0.1:5432:5432"
    command: ["postgres", "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"]

  app:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: scada_repo
      DATABASE_URL: "postgres://postgres:pass@db:5432/scada_repo"
    networks:
      - global
    ports:
      - "4020:4020"
    entrypoint: ["/app/entrypoint.sh"]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - global

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    networks:
      - global
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  db_data:
  grafana_data:
