apiVersion: 1

datasources:
  - name: ScadaDB
    type: postgres
    access: proxy
    url: db:5432
    database: scada_repo
    user: grafana_user
    secureJsonData:
      password: grafana_pass
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1500