apiVersion: 1

datasources:
  - name: MyPostgres
    type: postgres
    access: proxy
    url: db:5432
    database: scada_repo
    user: postgres
    secureJsonData:
      password: pass
    isDefault: true