{
 "title": "SCADA",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Fetching time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    MAX(fetching_time) AS max,\r\n    AVG(fetching_time) AS avg,\r\n    MIN(fetching_time) AS min\r\nFROM fetching_times\r\nWHERE $__timeFilter(inserted_at)"
    }
   ]
  },
  {
   "title": "App CPU usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    MAX(cpu_utilization_percent) AS max,\r\n    AVG(cpu_utilization_percent) AS avg,\r\n    MIN(cpu_utilization_percent) AS min\r\nFROM metrics\r\nWHERE $__timeFilter(recorded_at)\r\n  AND container_title = 'scada-app-1'"
    }
   ]
  },
  {
   "title": "Db CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    MAX(cpu_utilization_percent) AS max,\r\n    AVG(cpu_utilization_percent) AS avg,\r\n    MIN(cpu_utilization_percent) AS min\r\nFROM metrics\r\nWHERE $__timeFilter(recorded_at)\r\n  AND container_title = 'scada-db-1'"
    }
   ]
  },
  {
   "title": "App RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    MAX(memory_usage_mb) AS max,\r\n    AVG(memory_usage_mb) AS avg,\r\n    MIN(memory_usage_mb) AS min\r\nFROM metrics\r\nWHERE $__timeFilter(recorded_at)\r\n  AND container_title = 'scada-app-1'"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT inserted_at AS time,\ncontainer_title AS metric,\ncpu_utilization_percent\nFROM metrics \nWHERE $__timeFilter(inserted_at) \nORDER BY inserted_at"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "rawSql": "SELECT inserted_at AS time,\r\ncontainer_title AS metric,\r\nmemory_usage_mb\r\nFROM metrics \r\nWHERE $__timeFilter(inserted_at) \r\nORDER BY inserted_at"
    }
   ]
  },
  {
   "title": "Db RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    MAX(memory_usage_mb) AS max,\r\n    AVG(memory_usage_mb) AS avg,\r\n    MIN(memory_usage_mb) AS min\r\nFROM metrics\r\nWHERE $__timeFilter(recorded_at)\r\n  AND container_title = 'scada-db-1'"
    }
   ]
  },
  {
   "title": "AC Grid",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT recorded_at as time, key as metric, value \r\nFROM data_points \r\nWHERE container_title = 'AC Grid' \r\nGROUP BY key, recorded_at, value \r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Li-Ion Battery",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT recorded_at as time, key as metric, value \r\nFROM data_points \r\nWHERE container_title = 'Li-Ion Battery' \r\nGROUP BY key, recorded_at, value \r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Weather Station",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT recorded_at as time, key as metric, value \r\nFROM data_points \r\nWHERE container_title = 'Weather Station' \r\nGROUP BY key, recorded_at, value \r\nORDER BY time"
    },
    {}
   ]
  },
  {
   "title": "AGM Battery",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT recorded_at as time, key as metric, value \r\nFROM data_points \r\nWHERE container_title = 'AGM Battery' \r\nGROUP BY key, recorded_at, value \r\nORDER BY time"
    }
   ]
  }
 ]
}